name    'jalli-xfce'
version '0.0.1'
source 'http://github.com/jalli/puppet-module-xfce'
author 'jalli'
license 'GNU General Public License, Version 3.0'
summary 'Setup XFCE Desktop Environment'
description 'Sets up a minimal XFCE Desktop Environment'
project_page 'http://github.com/jalli/puppet-module-xfce'
